apiVersion: v1
kind: Secret
metadata:
  name: healio-secrets
  namespace: healio
type: Opaque
stringData:
  JWT_SECRET: REPLACE_WITH_YOUR_JWT_SECRET
  STRIPE_SECRET_KEY: REPLACE_WITH_YOUR_STRIPE_KEY
  SMTP_USER: REPLACE_WITH_YOUR_EMAIL
  SMTP_PASS: REPLACE_WITH_YOUR_EMAIL_APP_PASSWORD
  TWILIO_ACCOUNT_SID: REPLACE_WITH_TWILIO_SID
  TWILIO_AUTH_TOKEN: REPLACE_WITH_TWILIO_TOKEN
  TWILIO_PHONE_NUMBER: REPLACE_WITH_TWILIO_PHONE