apiVersion: v1
kind: Secret
metadata:
  name: healio-secrets
  namespace: healio
type: Opaque
stringData:
  JWT_SECRET: "ugHI6rjFYbveqfaWlSHP6jiz4nKuXGDP"
  STRIPE_SECRET_KEY: "sk_test_51TLjurAsszpjM13DPXC07Z7CQahDEU71IQooJNAOwFs9TdP6hOQxN9cj0UM2z4jTN4mJqmIPxgVCeQFTdNGWjZeL00qrAjndbr"
  STRIPE_WEBHOOK_SECRET: "whsec_WOAUdfYOHP504CgZrU2ovdhGXWKp7PlC"
  CLOUDINARY_CLOUD_NAME: "ds5c0o49f"
  CLOUDINARY_API_KEY: "962439637132256"
  CLOUDINARY_API_SECRET: "Y9neNXRjyQOjFkcIsXYni8-O7cw"
  SMTP_USER: "nisharasenadheera0000@gmail.com"
  SMTP_PASS: "phgu ywhm svth fler"
  NOTIFY_LK_USER_ID: "31483"
  NOTIFY_LK_API_KEY: "W3rYKVAfm37SqQomapRi"
