apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: healio/patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: healio-configmap
                  key: MONGODB_URI_PATIENT
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healio
spec:
  selector:
    app: patient-service
  ports:
    - port: 4002
      targetPort: 4002
  clusterIP: None