apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: healio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: healio/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
          env:
            - name: PORT
              value: "5006"
            - name: MONGO_PAYMENT_URI
              valueFrom:
                configMapKeyRef:
                  name: healio-configmap
                  key: MONGO_PAYMENT_URI
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: healio-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: healio-secrets
                  key: STRIPE_WEBHOOK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: healio
spec:
  selector:
    app: payment-service
  ports:
    - port: 5006
      targetPort: 5006
  clusterIP: None
